# Generated by Django 5.0.6 on 2024-07-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_alter_cartitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_item',
        ),
    ]
